fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: 'email@gmail.com' # for example your email
        sender_name: 'email@gmail.com' # for example your email