# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest: 
    routing_loader:
        default_format: json
        include_format: false
    body_listener: true
    format_listener:
          rules:
              - { path: '^/api/doc', priorities: ['html'], fallback_format: html, prefer_extension: false }
              - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
              - { path: '^/oauth', priorities: ['json'], fallback_format: json, prefer_extension: false }
              - { path: '^/', stop: true }  
    param_fetcher_listener: true
    access_denied_listener:
        json: true
    view:
        view_response_listener: true
        formats:
            json: true
        templating_formats:
            html: true
        default_engine: twig
